= jhipster

This application was generated using JHipster 5.8.2, you can find documentation and help at https://www.jhipster.tech/documentation-archive/v5.8.2[https://www.jhipster.tech/documentation-archive/v5.8.2].

== Development

Before you can build this project, you must install and configure the following dependencies on your machine:

. https://nodejs.org/[Node.js]: We use Node to run a development web server and build the project.
Depending on your system, you can install Node either from source or as a pre-packaged bundle.

After installing Node, you should be able to run the following command to install development tools.
You will only need to run this command when dependencies change in link:package.json[package.json].

[source]
----
npm install
----

We use npm scripts and https://webpack.github.io/[Webpack] as our build system.

Run the following commands in two separate terminals to create a blissful development experience where your browser
auto-refreshes when files change on your hard drive.

[source]
----
./gradlew
npm start
----

Npm is also used to manage CSS and JavaScript dependencies used in this application. You can upgrade dependencies by
specifying a newer version in link:package.json[package.json]. You can also run `npm update` and `npm install` to manage dependencies.
Add the `help` flag on any command to see how you can use it. For example, `npm help update`.

The `npm run` command will list all of the scripts available to run for this project.

=== Service workers

Service workers are commented by default, to enable them please uncomment the following code.

* The service worker registering script in index.html
[source,html]
----
<script>
    if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register('./service-worker.js').then(function() {
            console.log('Service Worker Registered');
        });
    }
</script>
----

Note: workbox creates the respective service worker and dynamically generate the `service-worker.js`

=== Managing dependencies

For example, to add http://leafletjs.com/[Leaflet] library as a runtime dependency of your application, you would run following command:

[source]
----
npm install --save --save-exact leaflet
----

To benefit from TypeScript type definitions from http://definitelytyped.org/[DefinitelyTyped] repository in development, you would run following command:

[source]
----
npm install --save-dev --save-exact @types/leaflet
----

Then you would import the JS and CSS files specified in library's installation instructions so that https://webpack.github.io/[Webpack] knows about them:
Edit link:src/main/webapp/app/vendor.ts[src/main/webapp/app/vendor.ts] file:

[source]
----
import 'leaflet/dist/leaflet.js';
----

Edit link:src/main/webapp/content/css/vendor.css[src/main/webapp/content/css/vendor.css] file:

[source]
----
@import '~leaflet/dist/leaflet.css';
----

Note: there are still few other things remaining to do for Leaflet that we won't detail here.

For further instructions on how to develop with JHipster, have a look at https://www.jhipster.tech/documentation-archive/v5.8.2/development/[Using JHipster in development].

=== Using angular-cli

You can also use https://cli.angular.io/[Angular CLI] to generate some custom client code.

For example, the following command:

[source]
----
ng generate component my-component
----

will generate few files:

[source]
----
create src/main/webapp/app/my-component/my-component.component.html
create src/main/webapp/app/my-component/my-component.component.ts
update src/main/webapp/app/app.module.ts
----

== Building for production

To optimize the jhipster application for production, run:

[source]
----
./gradlew -Pprod clean bootWar
----

This will concatenate and minify the client CSS and JavaScript files. It will also modify `index.html` so it references these new files.
To ensure everything worked, run:

[source]
----
java -jar build/libs/*.war
----

Then navigate to http://localhost:8080[http://localhost:8080] in your browser.

Refer to https://www.jhipster.tech/documentation-archive/v5.8.2/production/[Using JHipster in production] for more details.

== Testing

To launch your application's tests, run:

[source]
----
./gradlew test
----

=== Client tests

Unit tests are run by https://facebook.github.io/jest/[Jest] and written with http://jasmine.github.io/2.0/introduction.html[Jasmine]. They're located in link:src/test/javascript/[src/test/javascript/] and can be run with:

[source]
----
npm test
----

For more information, refer to the https://www.jhipster.tech/documentation-archive/v5.8.2/running-tests/[Running tests page].

=== Code quality

Sonar is used to analyse code quality. You can start a local Sonar server (accessible on http://localhost:9001[http://localhost:9001]) with:

[source]
----
docker-compose -f src/main/docker/sonar.yml up -d
----

Then, run a Sonar analysis:

[source]
----
./gradlew -Pprod clean test sonarqube
----

For more information, refer to the https://www.jhipster.tech/documentation-archive/v5.8.2/code-quality/[Code quality page].

== Using Docker to simplify development (optional)

You can use Docker to improve your JHipster development experience. A number of docker-compose configuration are available in the link:src/main/docker[src/main/docker] folder to launch required third party services.

For example, to start a mysql database in a docker container, run:

[source]
----
docker-compose -f src/main/docker/mysql.yml up -d
----

To stop it and remove the container, run:

[source]
----
docker-compose -f src/main/docker/mysql.yml down
----

You can also fully dockerize your application and all the services that it depends on.
To achieve this, first build a docker image of your app by running:

[source]
----
./gradlew bootWar -Pprod jibDockerBuild
----

Then run:

[source]
----
docker-compose -f src/main/docker/app.yml up -d
----

For more information refer to https://www.jhipster.tech/documentation-archive/v5.8.2/docker-compose[Using Docker and Docker-Compose], this page also contains information on the docker-compose sub-generator (`jhipster docker-compose`), which is able to generate docker configurations for one or several JHipster applications.

== Continuous Integration (optional)

To configure CI for your project, run the ci-cd sub-generator (`jhipster ci-cd`), this will let you generate configuration files for a number of Continuous Integration systems. Consult the https://www.jhipster.tech/documentation-archive/v5.8.2/setting-up-ci/[Setting up Continuous Integration] page for more information.

== Run Standalone Liquibase Command Line

----
cd src/main/resources
java -cp "../../../build/lib/*" liquibase.integration.commandline.Main \
--changeLogFile=src/main/resources/config/liquibase/master.xml \
--driver=com.mysql.jdbc.Driver \
--url=jdbc:mysql://localhost:3306/zemiandb \
--username=zemiandb \
--password=zemiandb123 \
update
----

== Things to Learn/Clarify

* Why IntelliJ import requires AndroidSDK?
    This could be ignore

* Why Gradle is not imported successfully?
    The error is likely due to wrong JDK is used. Ensure during project import
    is using JDK 1.8
